/*!  Copyright 2017 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/action-types",[],function(){var a={};a.ENABLE_STUDY_TRACKER="ENABLE_STUDY_TRACKER";a.DISABLE_STUDY_TRACKER="DISABLE_STUDY_TRACKER";return a});
/*!  Copyright 2017 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/selectors",[],function(){var a={};a.TRACKER_LS_KEY="SMAPoweredBy.enableStudyTracker";a.TRACKET_ENABLED_LS_VALUE="yes";a.TRACKET_DISABLED_LS_VALUE="no";a.isTrackingEnabled=function(){return false};return a});
/*!  Copyright 2018 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/ad-usage",["DS/Usage/UsageManager","DS/Usage/TrackerAPI"],function(d,f){var c={};var a=true,b="/upload",h="SIMABQX_AP",g={counter:"counter",timer:"timer"};function i(k){if(a){try{d.init({uploadPath:k.uploadPath||b,service:k.service||h});f.init()}catch(j){console.error(j);a=false}}}function e(j){var k;i(j);if(j.item&&a){k=f.getTracker(g.counter,j.item)}return k}c.getCounterTracker=e;return c});
/*!  Copyright 2017 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/actions",["DS/SMAPoweredByTracker/ad-tracker/action-types"],function(b){var a={};a.enableStudyTracker=function(){return{type:b.ENABLE_STUDY_TRACKER}};a.disableStudyTracker=function(){return{type:b.DISABLE_STUDY_TRACKER}};return a});
/*!  Copyright 2017 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/reducer",["DS/SMAPoweredByTracker/ad-tracker/action-types","DS/SMAPoweredByTracker/ad-tracker/selectors","DS/SMAPoweredByState/ad-state-utils"],function(e,c,d){var b={};const a={};function f(h,g){var i;if(typeof h==="undefined"){i=d.deepCopy(a)}else{i={};switch(g.type){case e.ENABLE_STUDY_TRACKER:if(!c.isTrackingEnabled()){window.localStorage.setItem(c.TRACKER_LS_KEY,c.TRACKET_ENABLED_LS_VALUE)}else{i=h}break;case e.DISABLE_STUDY_TRACKER:if(c.isTrackingEnabled()){window.localStorage.setItem(c.TRACKER_LS_KEY,c.TRACKET_DISABLED_LS_VALUE)}else{i=h}break;default:i=h;break}}return i}b["default"]=f;return b});
/*!  Copyright 2017 Dassault Systemes. All rights reserved. */
define("DS/SMAPoweredByTracker/ad-tracker/ad-usage-tracker",["DS/SMAPoweredByTracker/ad-tracker/selectors","DS/SMAPoweredByTracker/ad-tracker/ad-usage","DS/SMAPoweredByState/ad-state-app/selectors","DS/SMAPoweredByState/ad-state-domain-jobs/selectors","DS/SMAPoweredByState/ad-state-domain-job-types/selectors","text!DS/SMAPoweredByTracker/assets/alerts_to_track.json"],function(k,h,e,j,n,c){var g={},f="START_JOB_FULFILLED",b=JSON.parse(c),l="SMAPoweredBy.usageStats.",i={abaqus:"Abaqus"},a=".",p={abaqus:"ABAQUS",custom:"CUSTOM"};function o(s,u){var r=null,q=null,t=p.custom;r=j.jobTypeId(s,u);q=n.jobTypeWithID(s,r);if(q&&q.title&&q.title===i.abaqus){t=p.abaqus}return t}function d(s,r){var t=null,q=l+r.type+a;if(b.indexOf(r.code)!==-1){t=q+r.code}else{if(r.type===f&&r.payload&&r.payload.jobID){t=q+o(s,r.payload.jobID)}}return t}function m(q){return function(r){return function(v){var s,w,u,t;t=k.isTrackingEnabled();if(t){w=d(q.getState(),v);if(w){u=h.getCounterTracker({item:w,tenant:e.currentPlatformID(q.getState())});if(u&&u.inc){u.inc()}}}s=r(v);return s}}}g["default"]=m;return g});